server.port: 8083
spring.application.name: api-tickets-v1
server.servlet.context-path: /api/v1
server.error.include-message: always
spring.mongodb.embedded.version: 3.5.5

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring.data.mongodb:
  host: localhost
  port: 27017
  database: wmmdb
  username: root
  password: password
  authentication-database: admin


logging:
  level:
    root: INFO
    com.example: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    de.flapdoodle.os.common.attributes: warn
---
spring.profile.active: docker
spring.data.mongodb:
  host: localhost
  port: 27017
  database: wmmdb
username: root
password: password
authentication-database: admin